// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lkjjkypbbsuuidjlfyit.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxrampreXBiYnN1dWlkamxmeWl0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2ODk4MDQsImV4cCI6MjA2MjI2NTgwNH0.pZb3LMFty05FtyvYZdBbrdEG6lBBPIO52rebFSebwB4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);